# Generated by Django 5.0 on 2024-09-22 11:40

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0002_alter_myuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=25)),
                ('prod_dsc', models.TextField(max_length=500)),
                ('prod_rating', models.FloatField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('prod_price', models.IntegerField()),
                ('prod_disc', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('prod_qty', models.IntegerField()),
                ('prod_main_cat', models.CharField(max_length=10)),
                ('prod_sub_cat', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odr_date', models.DateField(default=datetime.date.today)),
                ('ship_addr', models.TextField(max_length=510)),
                ('status', models.CharField(choices=[('OC', 'Order Confirmed'), ('SH', 'Shipped'), ('OD', 'Out for Dilevery'), ('DI', 'Dilevered')], default='OC', max_length=2)),
                ('mode_of_payment', models.CharField(choices=[('DBC', 'Debit Card'), ('CRC', 'Credit Card'), ('UPI', 'Online'), ('COD', 'Cash on Dilevery'), ('NBI', 'Net banking')], default='DC', max_length=3)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='qmart.products')),
            ],
        ),
    ]
