# Generated by Django 5.0 on 2024-09-23 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0003_products_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prod_qty',
            new_name='prod_avl_qty',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_qty', models.IntegerField()),
                ('cart_customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='qmart.products')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='Media/')),
                ('img_pro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='qmart.products')),
            ],
        ),
    ]
