# Generated by Django 5.0 on 2024-09-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0004_rename_prod_qty_products_prod_avl_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='img_pro',
        ),
    ]
