# Generated by Django 5.0 on 2024-09-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0005_remove_images_img_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(max_length=500, upload_to='Media/'),
        ),
    ]
