# Generated by Django 5.0 on 2024-09-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0006_alter_images_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
