# Generated by Django 5.0 on 2024-09-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0009_category_remove_products_prod_main_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_cat',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_cat',
            field=models.CharField(max_length=25),
        ),
    ]
