# Generated by Django 5.0 on 2024-09-24 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0011_products_pro_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pro_cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='qmart.category'),
        ),
    ]
