# Generated by Django 5.0 on 2024-09-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0012_alter_products_pro_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_name',
            field=models.CharField(max_length=100),
        ),
    ]
