# Generated by Django 5.0 on 2024-09-27 04:08

import qmart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0014_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(max_length=500, upload_to=qmart.models.Images.get_image_path),
        ),
    ]
