# Generated by Django 5.0 on 2024-09-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0015_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_name',
            field=models.CharField(max_length=255),
        ),
    ]
