# Generated by Django 5.0 on 2024-09-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0016_alter_products_prod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, default=' ', max_length=10, unique=True),
        ),
    ]
