# Generated by Django 5.0 on 2024-09-30 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0018_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pro_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='qmart.category'),
        ),
    ]
