# Generated by Django 5.0 on 2024-09-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0019_alter_products_pro_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='mode_of_payment',
            field=models.CharField(choices=[('DBC', 'Debit Card'), ('CRC', 'Credit Card'), ('UPI', 'Online'), ('COD', 'Cash on Dilevery'), ('NBI', 'Net banking')], max_length=3),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('OP', 'Order Placed'), ('SH', 'Shipped'), ('OD', 'Out for Dilevery'), ('DI', 'Dilevered')], default='OP', max_length=2),
        ),
    ]
