# Generated by Django 5.0 on 2024-09-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0020_alter_orders_mode_of_payment_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ord_qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, default=' ', max_length=20),
        ),
    ]
