# Generated by Django 5.0 on 2024-09-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0021_orders_ord_qty_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, default=' ', max_length=10),
        ),
    ]
