# Generated by Django 5.0 on 2024-09-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0023_alter_myuser_phone_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, default=' ', max_length=20),
        ),
    ]
