# Generated by Django 5.0 on 2024-10-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0025_coupons_used_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='mode_of_payment',
            field=models.CharField(choices=[('PPL', 'Debit Card'), ('CRC', 'Credit Card'), ('UPI', 'Online'), ('COD', 'Cash on Dilevery')], max_length=3),
        ),
    ]
