# Generated by Django 5.0 on 2024-10-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0026_alter_orders_mode_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('OP', 'Order Placed'), ('SH', 'Shipped'), ('OD', 'Out for Dilevery'), ('DI', 'Dilevered'), ('CL', 'Canceled')], default='OP', max_length=2),
        ),
    ]
