# Generated by Django 5.0 on 2024-10-03 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0027_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='coupon_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='qmart.coupons'),
        ),
        migrations.AddField(
            model_name='orders',
            name='ord_id',
            field=models.IntegerField(default=1),
        ),
    ]
