# Generated by Django 5.0 on 2024-10-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0028_orders_coupon_used_orders_ord_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='coupon_used',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='ord_id',
        ),
    ]
