# Generated by Django 5.0 on 2024-10-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0029_remove_orders_coupon_used_remove_orders_ord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('OP', 'Order Placed'), ('SH', 'Shipped'), ('OD', 'Out for Dilevery'), ('DI', 'Dilevered')], default='OP', max_length=2),
        ),
    ]
