# Generated by Django 5.0 on 2024-10-03 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmart', '0030_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qmart.products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('OP', 'Order Placed'), ('SH', 'Shipped'), ('OD', 'Out for Dilevery'), ('DI', 'Delivered')], default='OP', max_length=2),
        ),
    ]
